keys:
  # # Users
  # - &users:
  #   - &kiara 12345PGPPUBLICKKEY
  # Hosts
  - &hosts:
    - &hammer age19ulsktcwmnh2xkt2jkm0e9h0p0cd5qepnsq6kdjcalspsp90538qvmw80m

creation_rules:
  - path_regex: secrets(\.enc)?\.yml$
    key_groups:
    - age:
      - *hammer
      # pgp:
      # - *kiara
