types:
  rs:
    line_comment_prefix: //
  sh:
    line_comment_prefix: "#"
  nix:
    line_comment_prefix: "#"
  py:
    line_comment_prefix: "#"
  rb:
    line_comment_prefix: "#"
keymap:
  normal:
    page_up:
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
      - "cursor::move_up"
    page_down:
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
      - "cursor::move_down"
